"""Auto-generated by audit_unused_files.py — deletes unused/duplicate assets."""
import os
BASE = r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2"
files = [
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\industry-automotive.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\industry-consumer.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\industry-medical.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\industry-proto.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-horizontal-white.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-horizontal.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-omni-cropped.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-omni-stacked-transparent.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-omni-stacked-white.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-omni-stacked-whitecard.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-omni-stacked.jpg",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-omni-transparent.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-omni-white.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-omni-white.svg",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-omni.svg",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-stacked-cropped.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-stacked-white.svg",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-stacked.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\logo-stacked.svg",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\product-lab-bottles.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\product-precision-molding.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\product-wash-bottles.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\service-cnc-vmc.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\service-tool-die.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\website-assets\10-Homepage-Hero-About-Workflow\service-2d-3d.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\website-assets\10-Homepage-Hero-About-Workflow\service-reverse-engineering.png",
    r"C:\Users\prave\CS\Personal projects\Omni Matrix\Version 2\website-assets\3-Products-Laboratory-Plasticware\hello.jpg",
]

deleted = 0
for f in files:
    if os.path.exists(f):
        os.remove(f)
        print("DELETED:", os.path.relpath(f, BASE))
        deleted += 1
print(f"\nDone. {deleted} files deleted.")
