"""
refresh_gallery.py
==================
Scans all website-assets subfolders and regenerates gallery-manifest.json.
Run this any time you add or remove images from the website-assets folders.

Usage:
    python refresh_gallery.py
"""

import os, json, time

BASE = os.path.dirname(os.path.abspath(__file__))  # tools/
ASSOC_BASE = os.path.join(BASE, "..")  # project root
ASSETS = os.path.join(ASSOC_BASE, "website-assets")

# Map each gallery "key" to its website-assets subfolder
# The key matches the data-gallery attribute used in the HTML
GALLERY_MAP = {
    # Products page (projects.html)
    "lab-products":      "3-Products-Laboratory-Plasticware",
    "injection-molds":   "4-Services-Injection-Molds",
    "press-tools":       "5-Services-Press-Tools",
    "die-casting":       "6-Services-Die-Casting",
    "jigs-fixtures":     "7-Services-Jigs-Fixtures",
    "spm-automation":    "8-Services-SPM-Automation",

    # Service pages (service1-6.html) — same folders, different pages
    "service1-gallery":  "4-Services-Injection-Molds",
    "service2-gallery":  "5-Services-Press-Tools",
    "service3-gallery":  "6-Services-Die-Casting",
    "service4-gallery":  "7-Services-Jigs-Fixtures",
    "service5-gallery":  "6-Services-Die-Casting",
    "service6-gallery":  "8-Services-SPM-Automation",
}

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif"}

manifest = {}
v = int(time.time())  # cache-buster: current unix timestamp

for key, folder_name in GALLERY_MAP.items():
    folder_path = os.path.join(ASSETS, folder_name)
    images = []
    if os.path.isdir(folder_path):
        for fname in sorted(os.listdir(folder_path)):
            ext = os.path.splitext(fname)[1].lower()
            if ext in IMAGE_EXTS:
                rel = f"../website-assets/{folder_name}/{fname}?v={v}"
                images.append(rel)
    manifest[key] = images

# Write as a JS file so it works when opened directly (file://) without a server
out_path = os.path.join(BASE, "..", "assets", "js", "gallery-data.js")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by refresh_gallery.py — do not edit manually.\n")
    f.write("// Run: python refresh_gallery.py  after adding/removing images.\n")
    f.write("window.GALLERY_MANIFEST = ")
    json.dump(manifest, f, indent=2)
    f.write(";\n")

# Also keep the JSON copy for reference
json_path = os.path.join(BASE, "..", "gallery-manifest.json")
with open(json_path, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2)

print(f"gallery-data.js updated — {sum(len(imgs) for imgs in manifest.values())} images across {len(manifest)} galleries.")
for k, imgs in manifest.items():
    print(f"  {k}: {len(imgs)} image(s)")

